// Game Data - 100+ combinations per age group

export const wordHuntWords: Record<string, Array<{ word: string; hint: string }>> = {
    '5-7': [
        { word: 'elma', hint: 'Kırmızı veya yeşil meyve' },
        { word: 'top', hint: 'Onunla oynarız' },
        { word: 'ev', hint: 'İçinde yaşarız' },
        { word: 'ayak', hint: 'Yürümek için' },
        { word: 'göz', hint: 'Görmek için' },
        { word: 'kedi', hint: 'Miyavlar' },
        { word: 'köpek', hint: 'Havlar' },
        { word: 'kuş', hint: 'Uçar' },
        { word: 'güneş', hint: 'Gökyüzünde parlar' },
        { word: 'ay', hint: 'Gece görürüz' },
        { word: 'araba', hint: 'Yolda gider' },
        { word: 'ağaç', hint: 'Yeşil yaprakları var' },
        { word: 'çiçek', hint: 'Güzel kokar' },
        { word: 'su', hint: 'İçeriz' },
        { word: 'baba', hint: 'Erkek ebeveyn' },
        { word: 'anne', hint: 'Kadın ebeveyn' },
        { word: 'bebek', hint: 'Küçük çocuk' },
        { word: 'oyuncak', hint: 'Oynarız' },
        { word: 'yılan', hint: 'Sürünür' },
        { word: 'balık', hint: 'Suda yaşar' },
        { word: 'kelebek', hint: 'Renkli uçar' },
        { word: 'arı', hint: 'Bal yapar' },
        { word: 'çanta', hint: 'Eşya taşırız' },
        { word: 'ayakkabı', hint: 'Ayağa giyilir' },
        { word: 'şapka', hint: 'Başa takılır' },
        { word: 'eldiven', hint: 'Ele giyilir' },
        { word: 'pasta', hint: 'Doğum günü tatlısı' },
        { word: 'dondurma', hint: 'Soğuk tatlı' },
        { word: 'süt', hint: 'Beyaz içecek' },
        { word: 'ekmek', hint: 'Her gün yeriz' },
        { word: 'kalem', hint: 'Yazarız' },
        { word: 'kitap', hint: 'Okuruz' },
        { word: 'masa', hint: 'Üstünde çalışırız' },
        { word: 'sandalye', hint: 'Otururuz' },
        { word: 'kapı', hint: 'Açar kaparız' },
        { word: 'pencere', hint: 'Dışarı bakarız' },
        { word: 'yastık', hint: 'Başımızı koyarız' },
        { word: 'yatak', hint: 'Uyuruz' },
        { word: 'battaniye', hint: 'Örtünürüz' },
        { word: 'bardak', hint: 'İçecek içeriz' },
        { word: 'tabak', hint: 'Yemek yeriz' },
        { word: 'kaşık', hint: 'Çorba içeriz' },
        { word: 'çatal', hint: 'Yemek yeriz' },
        { word: 'bıçak', hint: 'Keseriz' },
        { word: 'tencere', hint: 'Yemek pişiririz' },
        { word: 'tava', hint: 'Kızartırız' },
        { word: 'buzdolabı', hint: 'Yiyecek soğutur' },
        { word: 'fırın', hint: 'Pişiririz' },
        { word: 'televizyon', hint: 'İzleriz' },
        { word: 'telefon', hint: 'Konuşuruz' },
        { word: 'saat', hint: 'Zamanı gösterir' },
        { word: 'ayna', hint: 'Kendimizi görürüz' },
        { word: 'sabun', hint: 'Temizleniriz' },
        { word: 'havlu', hint: 'Kurularız' },
        { word: 'diş', hint: 'Ağzımızda' },
        { word: 'el', hint: 'Tutarız' },
        { word: 'kol', hint: 'Vücudumuzda' },
        { word: 'bacak', hint: 'Yürürüz' },
        { word: 'baş', hint: 'Düşünürüz' },
        { word: 'saç', hint: 'Başımızda' },
        { word: 'kulak', hint: 'Duyarız' },
        { word: 'burun', hint: 'Koklarız' },
        { word: 'ağız', hint: 'Konuşuruz' },
        { word: 'dil', hint: 'Tadarız' },
        { word: 'kalp', hint: 'Atar' },
        { word: 'karın', hint: 'Yemek gider' },
        { word: 'parmak', hint: 'Elimizde' },
        { word: 'tırnak', hint: 'Parmakta' },
        { word: 'tavuk', hint: 'Gıdaklar' },
        { word: 'horoz', hint: 'Öter' },
        { word: 'ördek', hint: 'Suda yüzer' },
        { word: 'kaz', hint: 'Gagalar' },
        { word: 'at', hint: 'Kişner' },
        { word: 'inek', hint: 'Süt verir' },
        { word: 'koyun', hint: 'Meeler' },
        { word: 'keçi', hint: 'Dağda yaşar' },
        { word: 'tavşan', hint: 'Havuç yer' },
        { word: 'fare', hint: 'Peynir yer' },
        { word: 'aslan', hint: 'Orman kralı' },
        { word: 'kaplan', hint: 'Çizgili' },
        { word: 'fil', hint: 'Büyük hayvan' },
        { word: 'zürafa', hint: 'Uzun boyunlu' },
        { word: 'maymun', hint: 'Ağaca tırmanır' },
        { word: 'penguen', hint: 'Buzda yaşar' },
        { word: 'timsah', hint: 'Suda bekler' },
        { word: 'yumurta', hint: 'Tavuk doğurur' },
        { word: 'peynir', hint: 'Sütten yapılır' },
        { word: 'yoğurt', hint: 'Beyaz tatlı' },
        { word: 'tereyağı', hint: 'Ekmeğe süreriz' },
        { word: 'bal', hint: 'Arı yapar' },
        { word: 'reçel', hint: 'Meyve tatlısı' },
        { word: 'çay', hint: 'Sıcak içecek' },
        { word: 'kahve', hint: 'Siyah içecek' },
        { word: 'meyve', hint: 'Ağaçta yetişir' },
        { word: 'sebze', hint: 'Bahçede yetişir' },
        { word: 'armut', hint: 'Sarı meyve' },
        { word: 'muz', hint: 'Uzun sarı meyve' },
        { word: 'portakal', hint: 'Turuncu meyve' },
        { word: 'üzüm', hint: 'Salkımda' },
        { word: 'kiraz', hint: 'Kırmızı küçük' },
    ],
    '8-10': [
        { word: 'bilgisayar', hint: 'Dijital cihaz' },
        { word: 'öğretmen', hint: 'Ders anlatır' },
        { word: 'öğrenci', hint: 'Ders dinler' },
        { word: 'okul', hint: 'Eğitim yeri' },
        { word: 'defter', hint: 'Yazı yazarız' },
        { word: 'silgi', hint: 'Sileriz' },
        { word: 'cetvel', hint: 'Çizgi çekeriz' },
        { word: 'müzik', hint: 'Dinleriz' },
        { word: 'dans', hint: 'Hareket ederiz' },
        { word: 'şarkı', hint: 'Söyleriz' },
        { word: 'park', hint: 'Oyun yerimiz' },
        { word: 'salıncak', hint: 'Sallanırız' },
        { word: 'kaydırak', hint: 'Kayarız' },
        { word: 'bisiklet', hint: 'İki tekerlekli' },
        { word: 'paten', hint: 'Tekerlekli ayak' },
        { word: 'deniz', hint: 'Büyük su' },
        { word: 'kumsal', hint: 'Plajda' },
        { word: 'yıldız', hint: 'Gece parlar' },
        { word: 'bulut', hint: 'Gökyüzünde' },
        { word: 'yağmur', hint: 'Gökten düşer' },
        { word: 'kar', hint: 'Beyaz soğuk' },
        { word: 'rüzgar', hint: 'Eser' },
        { word: 'fırtına', hint: 'Şiddetli hava' },
        { word: 'gökkuşağı', hint: 'Renkli yay' },
        { word: 'şimşek', hint: 'Işık çakar' },
        { word: 'gök', hint: 'Yukarıda' },
        { word: 'dünya', hint: 'Gezegenimiz' },
        { word: 'gezegen', hint: 'Uzayda döner' },
        { word: 'uzay', hint: 'Yıldızlar var' },
        { word: 'roket', hint: 'Uzaya gider' },
        { word: 'astronot', hint: 'Uzaya çıkar' },
        { word: 'robot', hint: 'Makine insan' },
        { word: 'uçak', hint: 'Gökte uçar' },
        { word: 'helikopter', hint: 'Pervane döner' },
        { word: 'gemi', hint: 'Denizde gider' },
        { word: 'tren', hint: 'Rayda gider' },
        { word: 'otobüs', hint: 'Yolcu taşır' },
        { word: 'taksi', hint: 'Sarı araba' },
        { word: 'ambulans', hint: 'Hasta taşır' },
        { word: 'itfaiye', hint: 'Yangın söndürür' },
        { word: 'polis', hint: 'Güvenlik sağlar' },
        { word: 'doktor', hint: 'Tedavi eder' },
        { word: 'hemşire', hint: 'Hastaya bakar' },
        { word: 'hastane', hint: 'Tedavi yeri' },
        { word: 'eczane', hint: 'İlaç satılır' },
        { word: 'market', hint: 'Alışveriş' },
        { word: 'restoran', hint: 'Yemek yeriz' },
        { word: 'otel', hint: 'Kalırız' },
        { word: 'havaalanı', hint: 'Uçak kalkar' },
        { word: 'istasyon', hint: 'Tren durur' },
        { word: 'müze', hint: 'Eser sergiler' },
        { word: 'kütüphane', hint: 'Kitap okuruz' },
        { word: 'sinema', hint: 'Film izleriz' },
        { word: 'tiyatro', hint: 'Oyun izleriz' },
        { word: 'stadyum', hint: 'Maç izleriz' },
        { word: 'spor', hint: 'Hareket ederiz' },
        { word: 'futbol', hint: 'Top oyunu' },
        { word: 'basketbol', hint: 'Pota oyunu' },
        { word: 'voleybol', hint: 'Ağ oyunu' },
        { word: 'tenis', hint: 'Raket oyunu' },
        { word: 'yüzme', hint: 'Suda spor' },
        { word: 'koşu', hint: 'Hızlı yürüme' },
        { word: 'atlama', hint: 'Zıplama' },
        { word: 'jimnastik', hint: 'Esneklik' },
        { word: 'buz', hint: 'Donmuş su' },
        { word: 'ateş', hint: 'Yanar' },
        { word: 'duman', hint: 'Ateşten çıkar' },
        { word: 'kül', hint: 'Yanmış madde' },
        { word: 'odun', hint: 'Ağaçtan' },
        { word: 'kömür', hint: 'Siyah yanar' },
        { word: 'elektrik', hint: 'Enerji verir' },
        { word: 'pil', hint: 'Enerji depolar' },
        { word: 'lamba', hint: 'Işık verir' },
        { word: 'mum', hint: 'Alevle yanar' },
        { word: 'kibrit', hint: 'Ateş yakar' },
        { word: 'çakmak', hint: 'Alev çıkarır' },
        { word: 'anahtar', hint: 'Kapı açar' },
        { word: 'kilit', hint: 'Kapıda' },
        { word: 'zil', hint: 'Ses çıkarır' },
        { word: 'kamera', hint: 'Fotoğraf çeker' },
        { word: 'fotoğraf', hint: 'Anı saklar' },
        { word: 'video', hint: 'Hareketli görüntü' },
        { word: 'oyun', hint: 'Eğleniriz' },
        { word: 'yarış', hint: 'Kazanan var' },
        { word: 'ödül', hint: 'Kazanınca alırız' },
        { word: 'kupa', hint: 'Şampiyona' },
        { word: 'madalya', hint: 'Boyuna takılır' },
        { word: 'rozet', hint: 'Göğse takılır' },
        { word: 'bayrak', hint: 'Ülke simgesi' },
        { word: 'harita', hint: 'Yerleri gösterir' },
        { word: 'pusula', hint: 'Yön gösterir' },
        { word: 'dürbün', hint: 'Uzağı görürüz' },
        { word: 'mikrofon', hint: 'Ses büyütür' },
        { word: 'hoparlör', hint: 'Ses yayar' },
        { word: 'kulaklık', hint: 'Dinleriz' },
        { word: 'piyano', hint: 'Tuşlu çalgı' },
        { word: 'gitar', hint: 'Telli çalgı' },
        { word: 'davul', hint: 'Vurmalı çalgı' },
        { word: 'keman', hint: 'Yayla çalınır' },
        { word: 'flüt', hint: 'Üflenir' },
    ],
    '11-13': [
        { word: 'algoritma', hint: 'Problem adımları' },
        { word: 'ekosistem', hint: 'Canlı çevre' },
        { word: 'metafor', hint: 'Benzetme' },
        { word: 'demokrasi', hint: 'Halk yönetimi' },
        { word: 'fotosentez', hint: 'Bitki besini' },
        { word: 'jeoloji', hint: 'Yer bilimi' },
        { word: 'astronomi', hint: 'Uzay bilimi' },
        { word: 'kültür', hint: 'Toplum yaşamı' },
        { word: 'edebiyat', hint: 'Yazın sanatı' },
        { word: 'felsefe', hint: 'Düşünce bilimi' },
        { word: 'psikoloji', hint: 'Ruh bilimi' },
        { word: 'sosyoloji', hint: 'Toplum bilimi' },
        { word: 'arkeoloji', hint: 'Kazı bilimi' },
        { word: 'biyoloji', hint: 'Canlı bilimi' },
        { word: 'kimya', hint: 'Madde bilimi' },
        { word: 'fizik', hint: 'Doğa bilimi' },
        { word: 'genetik', hint: 'Kalıtım bilimi' },
        { word: 'hücre', hint: 'Canlı birimi' },
        { word: 'atom', hint: 'Madde parçası' },
        { word: 'molekül', hint: 'Atom birleşimi' },
        { word: 'enerji', hint: 'İş gücü' },
        { word: 'kuvvet', hint: 'İtme çekme' },
        { word: 'kütle', hint: 'Madde miktarı' },
        { word: 'hacim', hint: 'Yer kaplama' },
        { word: 'yoğunluk', hint: 'Kütle/hacim' },
        { word: 'sıcaklık', hint: 'Isı derecesi' },
        { word: 'basınç', hint: 'Kuvvet/alan' },
        { word: 'elektron', hint: 'Negatif parça' },
        { word: 'proton', hint: 'Pozitif parça' },
        { word: 'nötron', hint: 'Nötr parça' },
        { word: 'çekirdek', hint: 'Atom merkezi' },
        { word: 'bileşik', hint: 'Element birleşimi' },
        { word: 'karışım', hint: 'Madde karışımı' },
        { word: 'çözelti', hint: 'Sıvı karışım' },
        { word: 'asit', hint: 'Ekşi madde' },
        { word: 'baz', hint: 'Kaygan madde' },
        { word: 'tuz', hint: 'Nötr madde' },
        { word: 'oksijen', hint: 'Solunum gazı' },
        { word: 'hidrojen', hint: 'Hafif gaz' },
        { word: 'karbon', hint: 'Canlı elementi' },
        { word: 'azot', hint: 'Hava gazı' },
        { word: 'erozyon', hint: 'Toprak aşınması' },
        { word: 'deprem', hint: 'Yer sarsıntısı' },
        { word: 'yanardağ', hint: 'Lav püskürür' },
        { word: 'tsunami', hint: 'Dev dalga' },
        { word: 'iklim', hint: 'Hava durumu' },
        { word: 'mevsim', hint: 'Yıl bölümü' },
        { word: 'ekvator', hint: 'Dünya ortası' },
        { word: 'kutup', hint: 'Dünya ucu' },
        { word: 'okyanus', hint: 'Büyük deniz' },
        { word: 'kıta', hint: 'Büyük kara' },
        { word: 'ada', hint: 'Su içinde kara' },
        { word: 'yarımada', hint: 'Üç tarafı su' },
        { word: 'körfez', hint: 'Karaya giren su' },
        { word: 'boğaz', hint: 'Dar su yolu' },
        { word: 'nehir', hint: 'Akan su' },
        { word: 'göl', hint: 'Durgun su' },
        { word: 'baraj', hint: 'Su engeli' },
        { word: 'şelale', hint: 'Düşen su' },
        { word: 'kaynak', hint: 'Su çıkışı' },
        { word: 'vadi', hint: 'Derin yer' },
        { word: 'plato', hint: 'Yüksek düzlük' },
        { word: 'ova', hint: 'Alçak düzlük' },
        { word: 'tepe', hint: 'Alçak yükselti' },
        { word: 'dağ', hint: 'Yüksek yer' },
        { word: 'zirve', hint: 'En yüksek nokta' },
        { word: 'mağara', hint: 'Yer altı boşluk' },
        { word: 'kanyon', hint: 'Derin yarık' },
        { word: 'çöl', hint: 'Kurak bölge' },
        { word: 'orman', hint: 'Ağaçlık alan' },
        { word: 'savan', hint: 'Çayır alan' },
        { word: 'tundra', hint: 'Soğuk bölge' },
        { word: 'taiga', hint: 'İğne ormanı' },
        { word: 'bataklık', hint: 'Sulu toprak' },
        { word: 'vaha', hint: 'Çöl yeşilliği' },
        { word: 'fosil', hint: 'Kalıntı' },
        { word: 'maden', hint: 'Yer altı zenginlik' },
        { word: 'petrol', hint: 'Sıvı yakıt' },
        { word: 'doğalgaz', hint: 'Gaz yakıt' },
        { word: 'kömür', hint: 'Katı yakıt' },
        { word: 'nükleer', hint: 'Atom enerjisi' },
        { word: 'güneş', hint: 'Işık kaynağı' },
        { word: 'rüzgar', hint: 'Hava hareketi' },
        { word: 'dalga', hint: 'Su hareketi' },
        { word: 'jeotermal', hint: 'Yer ısısı' },
        { word: 'biyokütle', hint: 'Canlı enerji' },
        { word: 'sera', hint: 'Cam ev' },
        { word: 'ozon', hint: 'Koruyucu tabaka' },
        { word: 'kirlilik', hint: 'Çevre bozulma' },
        { word: 'geri dönüşüm', hint: 'Yeniden kullanım' },
        { word: 'sürdürülebilir', hint: 'Kalıcı' },
        { word: 'yenilenebilir', hint: 'Tükenmez' },
        { word: 'koruma', hint: 'Sahip çıkma' },
        { word: 'habitat', hint: 'Yaşam alanı' },
        { word: 'nesil', hint: 'Kuşak' },
        { word: 'soyu tükenen', hint: 'Yok olan' },
        { word: 'biyoçeşitlilik', hint: 'Canlı çeşidi' },
        { word: 'sığınak', hint: 'Koruma yeri' },
        { word: 'göç', hint: 'Yer değiştirme' },
        { word: 'adaptasyon', hint: 'Uyum' },
    ],
};

export const hangmanWords: Record<string, Array<{ word: string; hint: string }>> = {
    '5-7': wordHuntWords['5-7'],
    '8-10': wordHuntWords['8-10'],
    '11-13': wordHuntWords['11-13'],
};

export const letterSortWords: Record<string, string[]> = {
    '5-7': wordHuntWords['5-7'].map(w => w.word),
    '8-10': wordHuntWords['8-10'].map(w => w.word),
    '11-13': wordHuntWords['11-13'].map(w => w.word),
};
